ALOS2_SCAN:
  det_stitch: 0
ERS_processing:
  ALOS2:
    SLC_factor: 2.0
  ALOS2_SCAN:
    SLC_factor: 2.0
  ALOS_SLC:
    SLC_factor: 0.02
  S1_TOPS:
    spec_div: 0
    spec_mode: 0
S1_TOPS:
  det_stitch: 0
SLC_align:
  region_cut: -999
geocode:
  threshold_geocode: 0.1
make_filter_intfs:
  ALOS:
    dec_factor: 2
    filter_wavelength: 20
  ALOS2:
    dec_factor: 2
    filter_wavelength: 200
  ALOS2_SCAN:
    azimuth_dec: 8
    dec_factor: 4
    filter_wavelength: 400
    range_dec: 4
  ALOS_SLC:
    dec_factor: 2
    filter_wavelength: 200
  CSK_RAW:
    dec_factor: 2
    filter_wavelength: 200
  CSK_SLC:
    dec_factor: 2
    filter_wavelength: 200
  ENVI:
    dec_factor: 2
    filter_wavelength: 200
  ERS:
    dec_factor: 2
    filter_wavelength: 200
  RS2:
    dec_factor: 1
    filter_wavelength: 100
  S1_STRIP:
    dec_factor: 2
    filter_wavelength: 200
  S1_TOPS:
    azimuth_dec: 2
    dec_factor: 2
    filter_wavelength: 200
    range_dec: 8
  TSX:
    dec_factor: 1
    filter_wavelength: 100
  compute_phase_gradient: 0
  correct_iono: 0
  iono_dsamp: 1
  iono_filt_azi: 1.0
  iono_filt_rng: 1.0
  iono_skip_est: 1
  switch_master: 0
make_topo_ra:
  ALOS:
    shift_topo: 1
  ALOS2:
    shift_topo: 0
  ALOS2_SCAN:
    shift_topo: 0
  ALOS_SLC:
    shift_topo: 1
  CSK_RAW:
    shift_topo: 0
  CSK_SLC:
    shift_topo: 0
  ERS:
    shift_topo: 1
  RS2:
    shift_topo: 0
  S1_STRIP:
    shift_topo: 0
  S1_TOPS:
    shift_topo: 0
  TSX:
    shift_topo: 0
  topo_interp_mode: 0
  topo_phase: 1
preprocess:
  earth_radius: -999
  fd1: -999
  near_range: -999
  num_patches: -999
processing_stage:
  proc_stage: 1
  skip_1: 0
  skip_2: 0
  skip_3: 0
  skip_4: 0
  skip_5: 0
  skip_6: 0
  skip_master: 0
  skip_stage: -999
unwrapping:
  defomax: 0
  mask_water: 1
  near_interp: 0
  threshold_snaphu: 0
